[package]
name = "rail"
version = "0.2.0"
authors = ["J.R. Hill <hiljusti@so.dang.cool>"]
description = "WIP concatenative language"
license = "GPL-2.0-only"

readme = "README.md"
homepage = "https://github.com/hiljusti/rail"
repository = "https://github.com/hiljusti/rail"
#documentation = "TODO"
keywords = ["stack", "cli"]
categories = []

edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "9.1.2"
