[package]
name = "rail-lang"
version = "0.4.4"
authors = ["J.R. Hill <hiljusti@so.dang.cool>"]
description = "WIP concatenative language"
license = "GPL-2.0-only"

readme = "README.md"
homepage = "https://github.com/hiljusti/rail"
repository = "https://github.com/hiljusti/rail"
#documentation = "TODO"
keywords = ["programming-language", "concatenative", "interpreter", "parser"]
categories = []

edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rail"

[[bin]]
name = "rail"
path = "src/main.rs"

[dependencies]
rustyline = "9.1.2"
